export * from '../pages/AlbumsPage/AlbumsPage'
export * from '../pages/PhotosPage/PhotosPage'
export * from './PostCommentsPage/PostCommentsPage'
export * from '../pages/PostDetailsPages/PostDetailsPages'
export * from '../pages/PostPage/PostPage'
export * from '../pages/UserDetailsPages/UserDetailsPage'
export * from '../pages/UserPage/UserPage'
export * from '../pages/UserPostPage/UserPostPage'
